//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyApp
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string CoursesEnrolled { get; set; }
        public System.DateTime DateEnrolled { get; set; }
    }
}
